package com.example.cityapiclient.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF0C0E0E)
val md_theme_dark_onPrimary = Color(0xFF233600)
val md_theme_dark_primaryContainer = Color(0xFF344e00)
val md_theme_dark_onPrimaryContainer = Color(0xFFc2f362)
val md_theme_dark_secondary = Color(0xFFc2caab)
val md_theme_dark_onSecondary = Color(0xFF2c331d)
val md_theme_dark_secondaryContainer = Color(0xFF424a32)
val md_theme_dark_onSecondaryContainer = Color(0xFFdee6c6)
val md_theme_dark_tertiary = Color(0xFFa0d0c8)
val md_theme_dark_onTertiary = Color(0xFF003732)
val md_theme_dark_tertiaryContainer = Color(0xFF204e49)
val md_theme_dark_onTertiaryContainer = Color(0xFFbcece4)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF0C0E0E)
val md_theme_dark_onBackground = Color(0xFFe4e3db)
val md_theme_dark_surface = Color(0xFF0C0E0E)
val md_theme_dark_onSurface = Color(0xFFe4e3db)

//this is my transparent card
val md_theme_dark_surfaceVariant = Color(0xB30C0E0E)

val md_theme_dark_onSurfaceVariant = Color(0xFFc6c8b9)
val md_theme_dark_outline = Color(0xFF8f9284)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1c18)
val md_theme_dark_inverseSurface = Color(0xFFe4e3db)
val md_theme_dark_inversePrimary = Color(0xFF476800)
val md_theme_dark_shadow = Color(0xFF000000)



val md_theme_light_primary = Color(0xFF476800)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFc2f362)
val md_theme_light_onPrimaryContainer = Color(0xFF121f00)
val md_theme_light_secondary = Color(0xFF596148)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdee6c6)
val md_theme_light_onSecondaryContainer = Color(0xFF171e09)
val md_theme_light_tertiary = Color(0xFF386660)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbcece4)
val md_theme_light_onTertiaryContainer = Color(0xFF00201c)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefdf4)
val md_theme_light_onBackground = Color(0xFF1b1c18)
val md_theme_light_surface = Color(0xFFfefdf4)
val md_theme_light_onSurface = Color(0xFF1b1c18)
val md_theme_light_surfaceVariant = Color(0xFFe2e4d4)
val md_theme_light_onSurfaceVariant = Color(0xFF45483d)
val md_theme_light_outline = Color(0xFF75786b)
val md_theme_light_inverseOnSurface = Color(0xFFf2f1e9)
val md_theme_light_inverseSurface = Color(0xFF30312c)
val md_theme_light_inversePrimary = Color(0xFFa6d647)
val md_theme_light_shadow = Color(0xFF000000)
